# Generated by Django 4.2.16 on 2026-03-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('short_description', models.CharField(max_length=500, verbose_name='簡短描述')),
                ('description', models.TextField(verbose_name='詳細描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原價')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品圖片')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='3D 模型檔案 (.glb)')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='規格項目')),
                ('value', models.CharField(max_length=200, verbose_name='規格值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
            options={
                'verbose_name': '技術規格',
                'verbose_name_plural': '技術規格',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='功能名稱')),
                ('description', models.TextField(verbose_name='功能說明')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='圖示 (Emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': '功能特點',
                'verbose_name_plural': '功能特點',
                'ordering': ['order'],
            },
        ),
    ]
