# Generated by Django 4.2.16 on 2026-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera_height',
            field=models.FloatField(default=0.5, help_text='控制前端 3D 模型檢視器的攝影機高度，預設 0.5。較大的模型可設 1.0~2.0。', verbose_name='3D 模型攝影機高度（Y 軸）'),
        ),
    ]
