# Generated by Django 4.2.16 on 2026-03-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(blank=True, default='', help_text='APP 連線的 AI 伺服器位址，例如：https://xxxx.devtunnels.ms 或 http://192.168.1.100:8081', max_length=500, verbose_name='AI 伺服器 URL')),
                ('note', models.TextField(blank=True, default='', help_text='說明目前伺服器狀態，例如：DevTunnel URL，每次重啟需更新', verbose_name='備註')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
            ],
            options={
                'verbose_name': 'APP 伺服器設定',
                'verbose_name_plural': 'APP 伺服器設定',
            },
        ),
    ]
