# Generated by Django 4.2.16 on 2026-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('body', models.TextField(verbose_name='內容')),
                ('type', models.CharField(choices=[('version_update', '版本更新'), ('maintenance', '系統維護'), ('new_feature', '新功能'), ('general', '一般通知')], default='general', max_length=20, verbose_name='類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='留空表示立即生效；設定後到達該時間才對 APP 可見', null=True, verbose_name='排程時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'APP 公告',
                'verbose_name_plural': 'APP 公告列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(blank=True, default='', help_text='APP 連線的 AI 伺服器位址，例如：https://xxxx.devtunnels.ms 或 http://192.168.1.100:8081', max_length=500, verbose_name='AI 伺服器 URL')),
                ('note', models.TextField(blank=True, default='', help_text='說明目前伺服器狀態，例如：DevTunnel URL，每次重啟需更新', verbose_name='備註')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
            ],
            options={
                'verbose_name': 'APP 伺服器設定',
                'verbose_name_plural': 'APP 伺服器設定',
            },
        ),
        migrations.CreateModel(
            name='ImpactFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(verbose_name='加速度合力 (m/s²)')),
                ('outcome', models.CharField(help_text='auto_dialed / cancelled', max_length=20, verbose_name='結果')),
                ('is_false_positive', models.BooleanField(default=False, verbose_name='是否誤判')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄時間')),
            ],
            options={
                'verbose_name': '撞擊回饋',
                'verbose_name_plural': '撞擊回饋記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
