# Generated by Django 4.2.16 on 2026-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_appannouncement_appserverconfig_impactfeedback'),
        ('content', '0004_appannouncement'),
    ]

    operations = [
    ]
