# Generated by Django 4.2.16 on 2026-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_merge_20260330_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('color', models.CharField(default='#6366f1', help_text='標籤顯示顏色（Hex 色碼）', max_length=20, verbose_name='顏色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '公告標籤',
                'verbose_name_plural': '公告標籤',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appannouncement',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text='勾選後，前台公告頁會顯示此公告', verbose_name='顯示於網站'),
        ),
        migrations.AddField(
            model_name='appannouncement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='content.announcementtag', verbose_name='標籤'),
        ),
    ]
