# Generated by Django 4.2.16 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='功能權限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', '超級管理員'), ('admin', '一般管理員')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
