# Generated by Django 4.2.16 on 2026-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('member_type', models.CharField(choices=[('reference', '原專案參考者'), ('developer', '開發團隊成員')], default='developer', max_length=20, verbose_name='成員類型')),
                ('role', models.CharField(max_length=100, verbose_name='職稱 / 負責領域')),
                ('bio', models.TextField(blank=True, verbose_name='個人簡介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='頭像')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub 連結')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn 連結')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顯示排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示中')),
            ],
            options={
                'verbose_name': '團隊成員',
                'verbose_name_plural': '團隊成員',
                'ordering': ['member_type', 'order'],
            },
        ),
    ]
