# Generated by Django 4.2.16 on 2026-03-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='頁面路徑')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='來源頁面')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='瀏覽時間')),
            ],
            options={
                'verbose_name': '頁面瀏覽',
                'verbose_name_plural': '頁面瀏覽',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除')], max_length=20, verbose_name='動作')),
                ('resource_type', models.CharField(max_length=100, verbose_name='資源類型')),
                ('resource_id', models.IntegerField(blank=True, null=True, verbose_name='資源 ID')),
                ('resource_name', models.CharField(blank=True, max_length=500, verbose_name='資源名稱')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '後台操作日誌',
                'verbose_name_plural': '後台操作日誌',
                'ordering': ['-timestamp'],
            },
        ),
    ]
