# Generated by Django 4.2.16 on 2026-03-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ecpay_trade_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='綠界交易編號'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款'), ('failed', '付款失敗'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='付款狀態'),
        ),
    ]
